### ISSUE TITLE
High mouse poll rates and CPI makes the controls act crazy

### ISSUE THREAD

**Issue by gnarlin** [virtual-programming/overlord-linux#25] opened 2017-01-15 18:38 UTC
I have a Roccat Kone XTD. Unless I set the mouse poll rating down to 125 and the CPI down to at least 800 or so the mouse clicks don't always register and the in-game camera swivels about super fast and uncontrollably. I hope you can fix it, but if you can't please at least mention it somewhere obvious since gamers like me often have high end hardware.

**Comment by ysblokje** [comment] 2017-01-15 18:54
Hi @gnarlin, 
This his been discussed to death on bug thread #7 . Don't count on any fix, ever.

**Comment by vpltd-peterm** [comment] 2017-01-15 18:57
Duplicate of #7 - Ysblokje, consider yourself warned.

**Closed by vpltd-peterm** 2017-01-15 18:57 UTC

**Comment by sigzegv** [comment] 2017-01-16 00:47
@vpltd-peterm, why are you warning Ysblokje ? Is it so irritating seeing someone telling the truth ?

**Comment by vpltd-peterm** [comment] 2017-01-16 01:27
See the rules of conduct on the front page, specifically:

Do not insult, harass, or demean any other member or the developers
Do not start "flame wars"
